language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
    -  awesome_bot --white-list 'http://copperdroid.isg.rhul.ac.uk/copperdroid/','http://sanddroid.xjtu.edu.cn/','http://www.foresafe.com/scan','https://github.com/BaiduSecurityLabs/ZjDroid','https://github.com/yangbean9/ZjDroid','https://appanalysis.org/download.html','http://user.informatik.uni-goettingen.de/~darp/drebin/','https://labs.mwrinfosecurity.com/tools/2012/03/16/mercury/' --allow-redirect --files README.md
